name: Laravel CI

on:
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # 🔥 Cambiado a 8.3 para que sea compatible con composer.lock
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Validate Composer
        run: composer validate --strict

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run Pint (Laravel style checker)
        run: vendor/bin/pint --test || true

      # Opcional: correr tests si existen
      - name: Run PHPUnit
        run: php artisan test --parallel || true
