name: Laravel CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: github_actions
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql, sqlite
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer.json
        if: ${{ hashFiles('**/composer.json') != '' }}
        run: composer validate --strict

      - name: Install Composer dependencies
        if: ${{ hashFiles('**/composer.json') != '' }}
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Prepare Laravel environment (if artisan exists)
        if: ${{ hashFiles('**/artisan') != '' }}
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: github_actions
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate || true
          php artisan config:clear || true

      - name: Setup Node.js (18)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci || npm install --legacy-peer-deps

      - name: Build assets
        run: npm run build

      - name: Wait for MySQL to be ready (if using DB)
        if: ${{ hashFiles('**/artisan') != '' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y default-mysql-client
          for i in $(seq 1 30); do
            mysql -h127.0.0.1 -uroot -proot -e "SELECT 1" && break
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Run migrations (if artisan)
        if: ${{ hashFiles('**/artisan') != '' && hashFiles('**/vendor/bin/phpunit') != '' }}
        run: php artisan migrate --force

      - name: Run Laravel Pint (style) - conditional
        if: ${{ hashFiles('**/vendor/bin/pint') != '' }}
        run: vendor/bin/pint --test

      - name: Run PHPUnit (if tests exist)
        if: ${{ hashFiles('**/vendor/bin/phpunit') != '' }}
        run: vendor/bin/phpunit --testsuite=Feature
